### ISSUE TITLE
Create Component for User Input

### ISSUE THREAD

**Issue by kamst01** [kamst01/typizer#8]
**Is your feature request related to a problem? Please describe.**
The user has no way to participate in the race. They need a way to input the quote.

**Describe the solution you'd like**
Add an input that checks to see if it matches the quote provided by the API. This should also provide colors for the text, so the user knows if they need to go back or not. 

**Todo:**
- [x] If the current typed character matches the quote, show green.
- [x] If the current typed character does not match the quote, show a red background, with a darker red text and underline the character.
- [x] If the current typed character does not match the quote, the user should not be able to type more than the one incorrect character. **_This is very strict_**, but it's what I've always wanted from a typing game.

Other styles are not important as they will probably change later.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
